development: 
  stripe_secret_key: 'sk_test_KedWfvW8dxSzu7nVfnNGnWTc00TO1TMj9c'
  stripe_publishable_key: 'pk_test_wyznL8RZN2AYesUxsuhIAhPR00ISF8CA9O'

production: 
  stripe_secret_key: 'sk_test_KedWfvW8dxSzu7nVfnNGnWTc00TO1TMj9c'
  stripe_publishable_key: 'pk_test_wyznL8RZN2AYesUxsuhIAhPR00ISF8CA9O'